;;; my-treesit.el --- Treesit setup                  -*- lexical-binding: t; -*-

(when (treesit-available-p)
  (require 'treesit)
  
  (when (treesit-ready-p 'bash t)
    (add-to-list 'major-mode-remap-alist '(sh-mode . bash-ts-mode)))
  (when (treesit-ready-p 'c t)
    (add-to-list 'major-mode-remap-alist '(c-mode . c-ts-mode)))
  (when (treesit-ready-p 'cpp t)
    (add-to-list 'major-mode-remap-alist '(c++-mode . c++-ts-mode)))
  (when (and (treesit-ready-p 'c t) (treesit-ready-p 'cpp t))
    (add-to-list 'major-mode-remap-alist '(c-or-c++-mode . c-or-c++-ts-mode)))
  (when (treesit-ready-p 'css t)
    (add-to-list 'major-mode-remap-alist '(css-mode . css-ts-mode)))
  (when (treesit-ready-p 'elixir t)
    (add-to-list 'major-mode-remap-alist '(elixir-mode . elixir-ts-mode)))
  (when (treesit-ready-p 'heex t)
    (add-to-list 'major-mode-remap-alist '(heex-mode . heex-ts-mode)))
  (when (treesit-ready-p 'html t)
    (add-to-list 'major-mode-remap-alist '(html-mode . html-ts-mode))
    (add-to-list 'major-mode-remap-alist '(mhtml-mode . html-ts-mode)))
  (when (treesit-ready-p 'java t)
    (add-to-list 'major-mode-remap-alist '(java-mode . java-ts-mode)))
  (when (treesit-ready-p 'javascript t)
    (add-to-list 'major-mode-remap-alist '(javascript-mode . js-ts-mode))
    (add-to-list 'major-mode-remap-alist '(js-mode . js-ts-mode)))
  (when (treesit-ready-p 'json t)
    (add-to-list 'major-mode-remap-alist '(json-mode . json-ts-mode)))
  (when (and (treesit-ready-p 'javascript t) (treesit-ready-p 'json t))
    (add-to-list 'major-mode-remap-alist '(js-json-mode . js-ts-mode)))
  (when (treesit-ready-p 'ruby t)
    (add-to-list 'major-mode-remap-alist '(ruby-mode . ruby-ts-mode)))
  (when (treesit-ready-p 'toml t)
    (add-to-list 'major-mode-remap-alist '(conf-toml-mode . toml-ts-mode)))
  (when (treesit-ready-p 'yaml t)
    (if (require 'yaml-mode nil t)
        (add-to-list 'major-mode-remap-alist '(yaml-mode . yaml-ts-mode))
      (require 'yaml-ts-mode)))
  (when (treesit-ready-p 'dockerfile t)
    (if (require 'dockerfile-mode nil t)
        (add-to-list 'major-mode-remap-alist '(dockerfile-mode . dockerfile-ts-mode))
      (require 'dockerfile-ts-mode))))

(provide 'my-treesit)
;;; my-window-setup.el ends here
